### ISSUE TITLE
Calling `accelerate config` requires me to install transformers, datasets, etc..

### ISSUE THREAD

**Issue by tcapelle** [huggingface/accelerate#423] opened 2022-06-03 07:37 UTC
### System Info
I am using accelerate in the context of fastai, and calling `accelerate config` made me install a bunch of dependencies that I don't need:
- transformers
- datasets

### Reproduction

Call 
`$ accelerate config`
on a fresh accelerate install

### Expected behavior

```Shell
This should just work.
```

**Comment by muellerzr** [comment] 2022-06-03 11:10
Duplicate of https://github.com/huggingface/accelerate/issues/403. For now please install from main, we're releasing the bugfix soon. CC @sgugger

**Closed by muellerzr** 2022-06-03 11:10 UTC
Labels: bug
