### ISSUE TITLE
Fastai distributed training example KeyError

### ISSUE THREAD

**Issue by Lazystinkdog** [huggingface/accelerate#846] opened 2022-11-11 21:28 UTC
### System Info

```Shell
- `Accelerate` version: 0.14.0
- Platform: Linux-5.10.147-133.644.amzn2.x86_64-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.20.2
- PyTorch version (GPU?): 1.12.0+cu102 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
       - same_network: False
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: False
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction
The following python file is the [fastai distributed training example](https://github.com/fastai/fastai/blob/master/nbs/examples/distrib.py) code, with the addition of the test() wrapper function and print statement.

fastai-tutorial.py:
```python
from fastai.vision.all import *
from fastai.distributed import *
from fastai.vision.models.xresnet import *

def test():
    print("downloading")
    return untar_data(URLs.IMAGEWOOF_320)

path = rank0_first(test)
dls = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    splitter=GrandparentSplitter(valid_name='val'),
    get_items=get_image_files, get_y=parent_label,
    item_tfms=[RandomResizedCrop(160), FlipItem(0.5)],
    batch_tfms=Normalize.from_stats(*imagenet_stats)
).dataloaders(path, path=path, bs=64)

learn = Learner(dls, xresnet50(n_out=10), metrics=[accuracy,top_k_accuracy]).to_fp16()
with learn.distrib_ctx():
    learn.fit_flat_cos(2, 1e-3, cbs=MixUp(0.1))
```
```bash
accelerate launch fastai-tutorial.py
```

### Expected behavior

```Shell
I expect the test() function to only be called once and the script to finish without any errors.

Instead "downloading" is printed twice and the script throws a KeyError at the end (see output below).
```

**Comment by Lazystinkdog** [comment] 2022-11-11 21:29
```python
downloading
downloading
epoch     train_loss  valid_loss  accuracy  top_k_accuracy  time    
0         2.205160    2.120142    0.249873  0.773282        00:44                                                                                
1         2.034135    1.860407    0.331552  0.832316        00:43                                                                                
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1063, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 642, in multi_gpu_launcher
    console.print_exception(suppress=[__file__], show_locals=False)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/other.py", line 102, in patch_environment
    del os.environ[key.upper()]
  File "/usr/lib/python3.8/os.py", line 691, in __delitem__
    raise KeyError(key) from None
KeyError: 'NO_PROXY'
```

**Comment by muellerzr** [comment] 2022-11-11 21:42
Re the first one, downloading is called twice because each worker needs access to the data, however the data is only downloaded the first time, the second is loaded in from the cache (hence rank0_first, it does it on the first rank then the rest). 

Just in case can you try again and uninstall `rich`? `pip uninstall rich -y` (just want to see the difference in the errors here though there shouldn't be a difference)

**Comment by Lazystinkdog** [comment] 2022-11-11 21:55
Hello, thank you for your fast answer. I did try to uninstall rich, but it is not installed.

Regarding the first one, [untar_data()](https://docs.fast.ai/data.external.html#untar_data) returns the path to the extracted data, so why would the print statement get called again?

**Comment by muellerzr** [comment] 2022-11-11 22:03
@Lazystinkdog because the first time it was called on the process home to GPU 0. It must be called again on the process home to GPU 1 so each GPU has access to that datapoint/path. However `untar_data` only downloads the tarfile on the first GPU. Since on the second GPU it sees that the file exists, it only returns the path instead of downloading it again. Does this make sense?

**Comment by Lazystinkdog** [comment] 2022-11-11 22:23
Any thoughts about the KeyError?

**Comment by muellerzr** [comment] 2022-11-11 22:26
@Lazystinkdog the team is off until Monday, I'll be looking at it then :)

**Comment by muellerzr** [comment] 2022-11-14 14:37
@Lazystinkdog I can't actually recreate this. *However* one thing I do find odd is `gpu_ids` is `None` here. Can you try running this again and setting gpu_ids to be:

```yaml
gpu_ids: all
```
in your config? You can modify it by doing `vim ~/.cache/huggingface/accelerate/default_config.yaml`

**Comment by muellerzr** [comment] 2022-11-14 15:55
Although that shouldn't modify it at all since `accelerate launch` will only set the `gpu_ids` if they're not `None`. Can you give a bit more information about your system? What are you running this on? `NO_PROXY` isn't a variable set by Accelerate so would love to know more about your system

**Comment by Lazystinkdog** [comment] 2022-11-15 13:38
I work inside a dev docker container on an AWS g3.8xlarge Instance. I did some further experimenting and found that the Issue originates from my side. In the docker image, the environment variables ```HTTP_PROXY``` and ```HTTPS_PROXY``` are set in both upper and lower case. So when
```python
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/other.py", line 102, in patch_environment
    del os.environ[key.upper()]
```
gets called, the system tries to delete the same variable twice. When I remove one version it works without any problems.
I'm sorry for submitting an Issue that is caused by my own code and thanks for your help :)

**Comment by muellerzr** [comment] 2022-11-15 13:43
Glad to see it's fixed!

**Comment by xzyaoi** [comment] 2022-11-28 20:55
I run into exact the same issue as well. I am wondering if we should/could avoid this happening on the accelerate side? For example maybe we don't have to call upper() and store all keys? (Probably I am wrong, but I don't understand why we need to upper keys?) - or check keys before deleting? (probably safer but might be slower?)

If either approach is desired, I'd love to add a PR.

**Comment by rossbucky** [comment] 2022-12-31 07:37
got the same issue. it would be great if we can fix it within accelerate.

**Comment by sgugger** [comment] 2023-01-03 10:45
cc @muellerzr

**Comment by muellerzr** [comment] 2023-01-03 13:15
@rossbucky any chance you could provide a reproducer for me on how you got the error? :)

**Comment by YangLin-George** [comment] 2023-01-14 13:22
Hi @muellerzr ,
    I had this issue and fixed it by removing the extra enviornment params (i.e., http_proxy, https_proxy, and no_proxy) while keeping the upper case ones (i.e., HTTP_PROXY and HTTPS_PROXY). It happened when I was running my script in an official pytorch 1.13.1 docker, with a config.json which defines the lower case proxies.

**Comment by lrh123lrh** [comment] 2023-02-08 07:23
I run into the same issue and have fixed by removing the lower case environment parameters. It would be great if the accelerate side could solve this.

**Comment by muellerzr** [comment] 2023-02-08 14:12
Hi @lrh123lrh, this is up to the user to ensure that these environment variables are set properly, as Accelerate does not touch these nor set/modify them at all

**Comment by dxoigmn** [comment] 2023-02-21 20:11
@muellerzr: I would argue the environment variables are set correctly. The problem is that they are case sensitive on Linux so `HTTP_PROXY` can be different from `http_proxy`. However, `patch_environment` makes the assumption they are case **insensitive** (by converting the environment variable name to uppercase) and thus the issue when one has more than one environment variable in upper/lower/mixed cases:
https://github.com/huggingface/accelerate/blob/ea36b7dcebd5292afba328291a2ec6361dbcfb9a/src/accelerate/utils/other.py#L110-L116

**Closed** 2023-03-27 15:06 UTC
Labels: bug, wontfix, solved
