### ISSUE TITLE
 Unexpected key(s) in state_dict: "module.

### ISSUE THREAD

**Issue by catqaq** [huggingface/accelerate#438] opened 2022-06-10 06:56 UTC
### System Info

```Shell
- `Accelerate` version: 0.6.1
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-debian-buster-sid
- Python version: 3.6.13
- Numpy version: 1.18.5
- PyTorch version (GPU?): 1.10.0+cu102 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1.use accelerate for 2 gpu traing
2.save model follow your official code:
`accelerator.wait_for_everyone()
                    unwrapped_model = accelerator.unwrap_model(model)
                    accelerator.save(unwrapped_model.state_dict(), save_path)`
3.load the model failed due to the "module." prefix of all parameters:
`model = accelerator.unwrap_model(model)
                        model.load_state_dict(torch.load(save_path))`
"encoder.embeddings.position_ids", "encoder.embeddings.word_embeddings.weight"
-->  "module.encoder.embeddings.position_ids", "module.encoder.embeddings.word_embeddings.weight"****

Related issue: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

### Expected behavior

```Shell
Save and load the model trained by accelerate without "module." prefix.
```

**Comment by pacman100** [comment] 2022-06-10 10:43
Hello, I am unable to reproduce the error, might have been fixed in the latest version. Could you try after upgrading to the latest version of `accelerate`?

**Comment by catqaq** [comment] 2022-06-13 06:54
Hi, I manually removed the "module." prefix. In DistributedDataParallel training, I can use torch origin API to save and load model weights with the "module" prefix. 
When using accelerate API to save the model weights, I can save unwrapped_model without "module" prefix which is exactly what we need. However, I can't load the model back in the DistributedDataParallel training environment(such as evaluating after ddp traing) whether using the ddp model or the unwrapped_model.

**Comment by pacman100** [comment] 2022-06-13 07:34
Hello, Please give a small script to reproduce the error quickly. It is not clear what the issue is.

**Comment by catqaq** [comment] 2022-06-13 11:29
Hello, the code is temporarily inconvenient to provide, don't worry about this problem, I can load the model parameters by manually removing the prefix.

**Comment by catqaq** [comment] 2022-06-14 08:52
Hi, thanks for your advice. should we save model.state_dict() or unwrapped_model.state_dict()?
What I want is save and load the model in DDP training environment, and load the model for inference in normal single cpu/gpu environment.

**Closed** 2022-07-18 15:06 UTC
Labels: bug
