### ISSUE TITLE
Regarding the problem that the accelerate library does not work in multiple routines

### ISSUE THREAD

**Issue by strangeuser0518** [huggingface/accelerate#45] opened 2021-04-24 09:25 UTC
I want to complete a task on 2 nodes and 4 GPUs.
I configured the config file as required （in 2 nodes）

In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-GPU, [2] TPU): 1
How many different machines will you use (use more than 1 for multi-node training)? [1]: 2
What is the rank of this machine (from 0 to the number of machines - 1 )? [0]: 0
What is the IP address of the machine that will host the main process? same IP
What is the port you will use to communicate with the main process? same port
How many processes in total will you use? [1]: 2
Do you wish to use FP16 (mixed precision)? [yes/NO]: yes

But when I run accelerate launch train.py on these two nodes, they do not cooperate.They will each complete the training task
i dont know and how  to  do.

In addition, is this related to the absolute path when I use (--data_dir --model --output_dir)?

**Comment by sgugger** [comment] 2021-04-26 12:01
Hi @strangeuser0518 , it seems to be a duplicate of #37 which was fixed recently. Could you try again with a source install and see if the problem is solved?
There is going to be a release this week with the fix.

**Closed** 2022-06-03 15:06 UTC
