### ISSUE TITLE
If I am optimizing more than one model, do I need to write "with accelerator.accumulate(model1) and accelerator.accumulate(model2)"?

### ISSUE THREAD

**Issue by ethansmith2000** [huggingface/accelerate#1428] opened 2023-05-12 23:31 UTC

**Comment by muellerzr** [comment] 2023-05-12 23:32
Duplicate of https://github.com/huggingface/accelerate/issues/1414

**Comment by ethansmith2000** [comment] 2023-05-12 23:33
@muellerzr Thank you

**Closed** 2023-06-20 15:06 UTC
