### ISSUE TITLE
Dataloader fetches data on all nodes in distributed training

### ISSUE THREAD

**Issue by geekyGoku** [huggingface/accelerate#2179] opened 2023-11-22 06:11 UTC
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.24.1
- Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.26.0
- PyTorch version (GPU?): 2.1.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 944.88 GB
- GPU type: NVIDIA A100 80GB PCIe
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: FSDP
	- mixed_precision: bf16
	- use_cpu: False
	- debug: False
	- num_processes: 256
	- machine_rank: 31
	- num_machines: 32
	- main_process_ip: 172.27.14.14
	- main_process_port: 8999
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_forward_prefetch': True, 'fsdp_limit_all_gathers': True, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'FULL_STATE_DICT', 'fsdp_transformer_layer_cls_to_wrap': 'LlamaDecoderLayer', 'fsdp_use_orig_params': True}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I recently updated my accelerate version and torch version from 0.20 (accelerate) and 2.0.1(torch) to latest 0.24, 2.1. After the updated Dataloader now tries to fetch data on all the nodes in a multimode training setup. I enabled all the flags for dispatching batches from main node. But still data is iterated on all nodes.

### Expected behavior

When flags for dispatch batches are enabled in mutinode training, only main process across all nodes should prepare and dispatch batch

**Comment by muellerzr** [comment] 2023-11-22 14:01
Duplicate of https://github.com/huggingface/accelerate/issues/2162 I believe/they are the same feature request :)

**Closed** 2023-12-31 15:06 UTC
