### ISSUE TITLE
Config class(decorated by dataclass) can not receive kwargs from the config dict.

### ISSUE THREAD

**Issue by wuyongfa-genius** [huggingface/accelerate#30] opened 2021-04-18 12:17 UTC
First thanks for your excellent work. But it seems that i have come across a very strange problem. After I finished "accelerate config", I launched my script using "accelerate launch my_script.py", and I got the error as follows:
```
Traceback (most recent call last):
  File "/home/wuyongfa/anaconda3/envs/mmdet/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/wuyongfa/anaconda3/envs/mmdet/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/wuyongfa/anaconda3/envs/mmdet/lib/python3.7/site-packages/accelerate/commands/launch.py", line 297, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/wuyongfa/anaconda3/envs/mmdet/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 61, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/wuyongfa/anaconda3/envs/mmdet/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 100, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'machine_rank'
```
I assume that this is because the BaseConfig class(decorated by dataclass) can not receive kwargs from the config dict. Could anyone help me to find why?

**Comment by sgugger** [comment] 2021-04-19 12:17
That is strange. Could you copy here the content of your config file? Should be in `~/.cache/huggingface/accelerate/defautl_config.yml`

**Comment by wuyongfa-genius** [comment] 2021-04-19 12:19
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 1

**Comment by sgugger** [comment] 2021-04-19 12:38
Could reproduce, and the fix has been merged in #31 .
Would you mind making a source install to check it solves your problem? I'll make a patch release with the fix as soon as we've confirmed it now works as intended.

**Comment by wuyongfa-genius** [comment] 2021-04-19 13:21
Thanks for your effort. It is Ok now. By the way, I have a question that "When a new epoch starts, can the accelerate automatically shuffle the dataset on each device like the old way `DistributedSampler.set_epoch(epoch) does`?"

**Comment by sgugger** [comment] 2021-04-19 13:25
If you defined your dataloader with `shuffle=True`, this will be done yes :-)
See the [blog post](https://huggingface.co/blog/accelerate-library) (section how does it work) for more details!

**Comment by sgugger** [comment] 2021-04-19 13:26
Closing the issue since you confirmed it resolved the problem.

**Closed by sgugger** 2021-04-19 13:25 UTC
